### ISSUE TITLE
demo page crashes safari and does freezes to firefox

### ISSUE THREAD

**Issue by hiteshjasani** [oakes/play-cljs#15]
Accessing https://oakes.github.io/play-cljs/ on a modern Macbook crashed Safari and caused Firefox to grind to a halt with intermittent periods where it wasn't beachballing.  Maybe consider breaking it into separate pages so that so many things aren't running all at once.

**Comment by oakes** [comment]
Ah, I see what you mean re: safari...that sucks :( You actually can see each example on a separate page, such as [this one](https://oakes.github.io/play-cljs/cljs/play-cljs.core/'c'animation.html), but I imagine a safari user wouldn't be able to find that since the tab seems to crash right away. I'll try experimenting to see if i can mitigate it.

**Comment by oakes** [comment]
It looks like this is no longer a problem in either safari or firefox...though I am not sure why. Let me know if you still experience problems in either browser. For now I'll close this.
