### ISSUE TITLE
(3D mode) Moving the camera

### ISSUE THREAD

**Issue by Jickelsen** [oakes/play-cljs#21]
I am trying out the new 3D mode, but feeling somewhat limited by not easily being able to move the camera. It also starts at 0 0 (unsure about z) so drawing is offset with half a window width.
I’ve tried eg.
    (. js/p5 Camera 100 100 -100) 
but it doesn’t seem to have the desired effect. I must admit to being quite rusty when it comes to cljs atm though.
However, preferably this function should be wrapped. 
http://p5js.org/reference/#/p5/camera

**Comment by oakes** [comment]
I'm using p5.js in instance mode so it doesn't define anything globally. Instead you must call functions on the p5 object, which you can get by calling get-renderer. So `(.camera (get-renderer game) 100 100 -100)` should work. I haven't documented this so that's my fault, I'll find a place to mention this in the docs when I get a chance.

**Comment by oakes** [comment]
I added an interactive example here:

https://oakes.github.io/play-cljs/cljs/play-cljs.core/get-renderer.html

**Comment by Jickelsen** [comment]
I’ve tried calling get-renderer but the Clojurescript compiler throws the following warning
`Use of undeclared Var home-wurld.core/get-renderer at line 15 src/home_wurld/core.cljs`

I’m using the default example, game is indeed defined so that’s not the isuse.

**Comment by oakes** [comment]
The `get-renderer` function is in play-cljs, so you need to use whatever alias it is under. I think in the template it is `p`, so you would write `p/get-renderer`.
